// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplwNZzBaEAAd4IzoqcjNuYf_irg3a710',
    appId: '1:74916193837:web:1c8455d2f1e469cdff7aa4',
    messagingSenderId: '74916193837',
    projectId: 'mytaskmanager-5b161',
    authDomain: 'mytaskmanager-5b161.firebaseapp.com',
    storageBucket: 'mytaskmanager-5b161.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApWmNL0nOK0uAJY5MFdwBX2r80kqj_tKw',
    appId: '1:74916193837:android:8df2c73fbb6ee181ff7aa4',
    messagingSenderId: '74916193837',
    projectId: 'mytaskmanager-5b161',
    storageBucket: 'mytaskmanager-5b161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZH-IcB7vAq_l6uGwabWCXxqokQ52tm0',
    appId: '1:74916193837:ios:77f5f46f266cb814ff7aa4',
    messagingSenderId: '74916193837',
    projectId: 'mytaskmanager-5b161',
    storageBucket: 'mytaskmanager-5b161.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZH-IcB7vAq_l6uGwabWCXxqokQ52tm0',
    appId: '1:74916193837:ios:77f5f46f266cb814ff7aa4',
    messagingSenderId: '74916193837',
    projectId: 'mytaskmanager-5b161',
    storageBucket: 'mytaskmanager-5b161.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBplwNZzBaEAAd4IzoqcjNuYf_irg3a710',
    appId: '1:74916193837:web:0383f4b890cdf0eaff7aa4',
    messagingSenderId: '74916193837',
    projectId: 'mytaskmanager-5b161',
    authDomain: 'mytaskmanager-5b161.firebaseapp.com',
    storageBucket: 'mytaskmanager-5b161.firebasestorage.app',
  );
}
